#!/bin/sh
sudo docker run -d -p 22 -p 8080:8080 -v /home/vagrant/projects/jules/docker/saltmaster/srv:/srv:ro -h salt -name salt pra/saltmaster /usr/bin/supervisord -n -c /etc/supervisord.conf
#sudo docker run -i -t -p 22 -p 8080 -h salt -name salt pra/saltmaster /bin/bash