#!/bin/sh
sudo docker run -d -p 22 -v /home/vagrant/projects/jules/docker/puppetmaster/environments/middleware_local:/etc/puppet/environments/middleware_local:ro -h minion -name minion -link saltmaster:salt -link puppet:puppet pra/minion
#sudo docker run -i -t -p 22 -h minion -name minion -link saltmaster:salt -link puppet:puppet pra/minion /bin/bash
