#!/bin/sh
sudo docker run -d -p 22 -h minion -name minion -link saltmaster:salt -link puppetmaster:puppet pra/minion
#sudo docker run -i -t -p 22 -h minion -name minion -link saltmaster:salt -link puppetmaster:puppet pra/minion /bin/bash
