#!/bin/sh
sudo docker run -d -p 22 -dns 127.0.0.1 -h minion.dockerlan -name minion -link salt:salt -link puppet:puppet pra/minion /usr/local/bin/run
#sudo docker run -i -t -p 22 -h minion -name minion -link saltmaster:salt -link puppet:puppet pra/minion /bin/bash
