#!/bin/sh
sudo docker run -d -p 22 -p 8140 -dns 127.0.0.1 -v /home/vagrant/projects/jules/docker/puppetmaster/environments/middleware_local:/etc/puppet/environments/middleware_local:ro -h puppet.dockerlan -name puppet -link salt:salt pra/puppetmaster /usr/local/bin/run
#sudo docker run -i -t -p 22 -h puppet -name puppet pra/puppetmaster -link salt:salt /bin/bash