#!/bin/sh
sudo docker run -d -p 22 -p 8140 -v /home/vagrant/projects/jules/docker/puppetmaster/environments/middleware_local:/etc/puppet/environments/middleware_local:ro -h puppet -name puppet pra/puppetmaster /usr/local/bin/run
#sudo docker run -i -t -p 22 -h puppet -name puppet pra/puppetmaster /bin/bash